---
title: "_data_cleaning"
format: html
---


```{r}
library(tidyverse)
library(arrow) 


df_pres_2007_1 <- read_parquet("DATA/pres_2007_1.parquet")

df_pres_2007_2 <- read_parquet("DATA/pres_2007_2.parquet")

df_pres_2017_1 <- read_parquet("DATA/pres_2017_1.parquet")

df_pres_2017_2 <- read_parquet("DATA/pres_2017_2.parquet")

df_pres_2022_1 <- read_parquet("DATA/pres_2022_1.parquet")

df_pres_2022_2 <- read_parquet("DATA/pres_2022_2.parquet")

glimpse(df_pres_2022_1)

colnames(df_pres_2017_1)

colnames(df_pres_2007_1)

colnames(df_pres_2022_1)

colnames(df_pres_2017_2)

```

```{r}
partis_mapping <- tribble(
  ~candidat, ~partie,
  "emmanuel_macron", "LREM",
  "marine_le_pen", "RN",
  #2017-2022
  "macron_emmanuel", "LREM",
  "le_pen_marine", "RN",
  "melenchon_jean_luc", "LFI",
  "zemmour_eric", "REC",
  "pecresse_valerie", "LR",
  "hidalgo_anne", "PS",
  "jadot_yannick", "EELV",
  "roussel_fabien", "PCF",
  "lassalle_jean", "RES",
  "dupont_aignan_nicolas", "DLF",
  "arthaud_nathalie", "LO",
  "poutou_philippe", "NPA",
  "fillon_francois", "LR",
  "hamon_benoit", "PS",
  "cheminade_jacques", "SP",
  "asselineau_francois", "UPR",
  # 2007
  "sarkozy_nicolas", "UMP",
  "royal_segolene", "PS",
  "bayrou_francois", "MoDem",
  "le_pen_jean_marie", "FN",
  "besancenot_olivier", "LCR",
  "de_villiers_philippe", "MPF",
  "buffet_marie_george", "PCF",
  "voynet_dominique", "Verts",
  "laguiller_arlette", "LO",
  "bove_jose", "DVG",
  "nihous_frederic", "CPNT",
  "schivardi_gerard", "PT"
)

clean_pres <- function(df_brut){
  df_propre <- df_brut |>
    rename(any_of(c(
      tour = "numero_tour",
      nb_inscr = "nb_inscrit",
      nb_emarg = "nb_emargement",
      nb_exprim = "nb_exprime"
    )))
  
  #pour les votes blancs et nuls
  if ("nb_vote_blanc" %in% names(df_propre)) {
    df_propre <- df_propre |>
      mutate(nb_bl_nul = nb_vote_blanc + nb_vote_nul)
  }
  else if ("nb_bl" %in% names(df_propre)) {
    df_propre <- df_propre |>
      mutate(nb_bl_nul = nb_bl + nb_nul)
  }
  
  candidats_presents <- intersect(names(df_propre), partis_mapping$candidat)
  
  df_final <- df_propre |>
    select(
      id_bvote, annee, tour, nb_inscr, nb_votant, nb_bl_nul, nb_exprim, 
      all_of(candidats_presents)
    ) |>
    mutate(type_election = "presidentiel") |>
  
  pivot_longer(
      cols = all_of(candidats_presents),
      names_to = "candidat",
      values_to = "voix"
    ) |>
  left_join(partis_mapping, by = "candidat")
  return(df_final)
}

clean_2007_1 <- clean_pres(df_pres_2007_1)
clean_2007_2 <- clean_pres(df_pres_2007_2)
clean_2017_1 <- clean_pres(df_pres_2017_1)
clean_2017_2 <- clean_pres(df_pres_2017_2)
clean_2022_1 <- clean_pres(df_pres_2022_1)
clean_2022_2 <- clean_pres(df_pres_2022_2)

mega_base_presidentielles <- bind_rows(
  clean_2007_1, clean_2007_2,
  clean_2017_1, clean_2017_2,
  clean_2022_1, clean_2022_2
)

glimpse(mega_base_presidentielles)

mega_base_presidentielles |> 
  count(annee, tour)


```