---
title: "Élections à Paris de 2007 à 2024"
format: revealjs
---

{{< include _load_data.qmd >}}
{{< include _utils.qmd >}}
{{< include _parties.qmd >}}

```{r}
#| label: presentation-libraries

library(gt)
library(patchwork)
library(factoextra)
library(sf)
library(broom)

```

## Élections sélectionnées

| Type d'élection | Années                 |
|-----------------|------------------------|
| Présentielles   | 2007, 2017, 2022       |
| Européennes     | 2014, 2024             |
| Législatives    | 2007, 2017, 2022, 2024 |

## Contenu du data set

```{r}
#| label: sample

elections |>
  filter(type == "presidentielles", year == 2017, round == 1) |>
  pluck("data", 1) |>
  select(!c(geo_shape, geo_point_2d)) |>
  rename_with(format_names) |>
  sample_n(5) |>
  gt() |>
  tab_header(title = "Élections présidentielles 2017, tour 1")

```

# Élections présidentielles -- PCA

```{r}
#| label: pca

pcomps <- elections |>
  mutate(
    pco = map(data, \(df) prcomp(candidates(df) |> top_n(6) |> rename_with(format_names), scale. = TRUE)),
    title = str_glue("{str_to_title(str_sub(type, end = 4))}. {year}, tour {round}")
  )

pcomps.pres <- filter(pcomps, type == "presidentielles", round == 1)
pcomps.euro <- filter(pcomps, type == "europeennes")

```

## Screeplots

```{r}
#| label: pca-pres-screeplot

pcomps.pres |>
  pmap(\(pco, title, ...) fviz_screeplot(pco, addlabels = TRUE, main = title, ylab = "Pourcentage de variance expliquée")) |>
  wrap_plots(axes = "collect")

```

## Cercles des corrélations

```{r}
#| label: pca-pres-var

pcomps.pres |>
  pmap(\(pco, title, ...) fviz_pca_var(pco, col.var = "royalblue", repel = TRUE, title = title)) |>
  wrap_plots(axes = "collect")

```

## Cartes

```{r}
#| label: choropleth

pcomps.pres |>
  filter(year != 2007) |>
  pmap(function(data, pco, title, ...) {
      bind_cols(data, pco$x) |>
      st_as_sf() |>
      ggplot(aes(fill = PC1)) +
      geom_sf() +
      scale_fill_gradient2(low = "blue", high = "red") +
      labs(title = title) +
      theme_void()
  }) |>
  wrap_plots()

```

# Élections européennes -- PCA

## Screeplots

```{r}
#| label: pca-euro-screeplot

pcomps.euro |>
  pmap(\(pco, title, ...) fviz_screeplot(pco, addlabels = TRUE, main = title, ylab = "Pourcentage de variance expliquée")) |>
  wrap_plots(axes = "collect")

```

## Biplots

```{r}
#| label: pca-euro-biplot

arrond_groups <- character()
arrond_groups[c(7, 8, 16, 17)] <- "ouest (7, 8, 16, 17)"
arrond_groups[c(1:6, 9:15, 18:20)] <- "pas ouest"

pcomps.euro |>
  pmap(function(pco, data, title, ...) {
    fviz_pca_biplot(
      pco, label = "var", col.var = "navy", title = title, repel = TRUE,
      habillage = factor(arrond_groups[data$num_arrond])
    ) +
    coord_fixed()
  }) |>
  wrap_plots(guides = "collect")

```

# Legislatives -- Clustering

```{r}
#| label: clustering-functions

legi_data <- function(select_year) {
  collect_election("legislatives", select_year, 1) |>
  rowwise() |>
  mutate(
    turnout = nb_votant / nb_inscr * 100,
    procu = nb_procu / nb_votant * 100,
    blanc = nb_bl_nul / nb_votant * 100,
    tmp = c_across(16:last_col()) |> sort(decreasing = TRUE) |> list(),
    best = tmp[1] / nb_votant * 100,
    second = tmp[2] / nb_votant * 100,
    gap = best - second,
    .keep = "unused"
  ) |>
  select(-tmp)
}

add_geo <- function(df) {
  if ("geo_shape" %in% names(df)) return(df)

  y <- df$annee[1]
  geo <- elections |>
    filter(type %in% c("presidentielles", "europeennes"), year == y, round == 1) |>
    pluck("data", 1) |>
    select(id_bvote, geo_shape, geo_point_2d)

  left_join(df, geo, by = "id_bvote")
}

cluster_analysis <- function(df) {
  set.seed(22)
  df <- df |>
    select(gap, blanc) |>
    scale() |>
    kmeans(centers = 3, nstart = 32L) |>
    augment(df)

  scatter <- ggplot(df, aes(x = gap, y = blanc, color = .cluster)) +
    geom_point() +
    labs(
      title = "Basé sur: Compétitivité (Gap) and Vote Blancs",
      x = "Écart entre le 1er et le 2ème candidat (%)",
      y = "Votes blancs et nuls (%)",
      color = "Cluster"
    ) +
    theme_minimal()

  map <- df |>
    add_geo() |>
    st_as_sf() |>
    ggplot(aes(fill = .cluster)) +
    geom_sf() +
    labs(
      title = str_c("Carte des clusters électoraux (", df$annee[1], ")"),
      fill = "Cluster"
    ) +
    theme_void()

  list(scatter, map)
}

```

## 2017

```{r}
#| label: clustering-2017

legi_data(2017) |> cluster_analysis() |> wrap_plots()

```

## 2024

```{r}
#| label: clustering-2024

legi_data(2024) |> cluster_analysis() |> wrap_plots()

```

# Legislatives 2024 -- Régression linéaire

```{r}
#| label: lin-reg

to_explain <- elections |>
  filter(type == "legislatives", year == 2024, round == 1) |>
  pluck("data") |>
  map(function(x) {
    x |>
    candidates(keep = id_bvote) |>
    top_n(1, start = 2)
  })
# misspelled name
to_explain[[1]] <- rename(to_explain[[1]], `maillard sylvain` = `7lard sylvain`)
names(to_explain) <- map_chr(to_explain, \(x) names(x)[2])

explicative_elections <- elections |>
  filter(year >= 2017, round == 1, !(type == "legislatives" & year == 2024)) |>
  select(type, year, round) |>
  unique()

regressions <- to_explain |>
  map(function(to_exp) {
    to_exp <- to_exp |> rename_with(\(x) str_c(x, "_exp"), .cols = -id_bvote)

    # Return the list of the six regressions using explicative_elections as explanatory variables
    explicative_elections |>
    pmap(function(type, year, round) {
      # Compute the linear regression of df using the election (type, year, round)
      collect_election(type, year, round) |>
        inner_join(x = to_exp, multiple = "any", by = "id_bvote") |>
        relocate(2, .after = nb_exprim) |>
        candidates(keep = id_bvote) |>
        column_to_rownames("id_bvote") |>
        lm(formula = str_glue("`{names(to_exp)[2]}` ~ ."))
    }) |>
    set_names(str_glue_data(explicative_elections, "{type}_{year}"))

  })

summaries <- map(regressions, \(x) map(x, summary))

```

## Meilleure élection explicative

```{r}
#| label: lin-reg-bar
#| lightbox:
#|  group: lin-reg-bar
#| layout-ncol: 5

summaries |>
  imap(function(regs, name) {
    map_dbl(regs, \(x) x$adj.r.squared) |>
    enframe(name = "election", value = "r_squared") |>
    mutate(fill = r_squared == max(r_squared)) |>
    ggplot(aes(x = election, y = r_squared, fill = fill)) +
    geom_col() +
    geom_text(aes(label = round(r_squared, 3)), vjust = -0.5) +
    labs(x = NULL, title = format_names(name)) +
    scale_fill_manual(values = c("lightgrey", "steelblue"), guide = "none") +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
      plot.title = element_text(size = 50, face = "bold")
    )
  }) |>
  walk(print)
```

## Cartes des résidus

```{r}
#| label: lin-reg-coef
#| lightbox:
#|  group: lin-reg-coef
#| layout-ncol: 5

coeffs <- summaries |>
  map("europeennes_2024") |>
  imap(function(reg, name) {
    reg$coefficients[-1, "Estimate"] |>
    enframe(name = "candidate", value = "coefficient") |>
    ggplot(aes(x = fct_reorder(format_names(candidate), coefficient, .desc = TRUE), y = coefficient)) +
    geom_col(fill = "steelblue") +
    labs(x = NULL, title = format_names(name)) +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
      plot.title = element_text(size = 50, face = "bold")
    )
  })

walk(coeffs, print)

```

##

```{r}
#| label: sandrine

coeffs$`rousseau sandrine`

```
